apiVersion: v1
kind: Service
metadata:
  name: {{ include "team-worker.fullname" . }}
  labels:
{{ include "team-worker.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "team-worker.name" . }}
    app.kubernetes.io/instance: {{ include "team-worker.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http

