apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal-worker-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "21"
spec:
  project: platform
  source:
    repoURL: registry-1.docker.io/temporalio
    chart: temporal-worker-controller
    targetRevision: 0.24.0
    helm:
      valuesObject:
        certmanager:
          install: false
  destination:
    server: https://kubernetes.default.svc
    namespace: temporal-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
